### ISSUE TITLE
Race Condition in Thread Class

### ISSUE THREAD

**Issue by pnicoletti88** [kgrolinger/se3313-2020-lab2#1]
Hi Professor,

I have found some behaviour which I believe to be troubling in the provided code. I stumbled across this as I was running a debugger, changing the timing of the code execution from what it would typically be. I am posting this here to both bring the issue to your attention and to save other students some time debugging this. I also could be wrong on this issue, and I apologize in advance if that is the case.

**Summary:**
The thread created by the thread class can call the virtual ThreadMain method before the child class has implemented it. This will crash the program.

**Explanation:**
In the constructor of the base thread class, a new thread is created and started - theThread(ThreadFunction, this). This thread gets started right away, first calling the ThreadFunction method, which then calls the virtual ThreadMain method. This introduces a race condition, as before the new thread can call the virtual method, the "parent" thread needs to have finished constructing the child class. This occurs as the base class is constructed before the child class. See sources for further explanation.

**Reproduction Steps:**
1) Uncomment provided code in Writer.cpp (see below)
2) Add sleep into Thread constructor (it can still happen occasionally without the sleep, but this makes it easier to reproduce)
3) Compile and run Writer

**Sources:**
https://stackoverflow.com/questions/962132/calling-virtual-functions-inside-constructors
https://stackoverflow.com/questions/5407304/error-pure-virtual-method-called-terminate-called-without-an-active-exception

**Output:**
![image](https://user-images.githubusercontent.com/46630768/95253338-3e126000-07ec-11eb-85b8-f16db828b8b3.png)

**Writer.cpp:**
![image](https://user-images.githubusercontent.com/46630768/95253743-d7da0d00-07ec-11eb-93f3-b211be4c04e9.png)

**thread.cpp constructor:**
![image](https://user-images.githubusercontent.com/46630768/95253779-e6c0bf80-07ec-11eb-8e5f-4f87f02a30d4.png)

**Comment by kgrolinger** [comment]
Used this code for two years with over 200 students. Looking into it.
